// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using catalog_service.Context;

#nullable disable

namespace catalog_service.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20260503205052_InitialMigrate")]
    partial class InitialMigrate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("catalog_service.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8f7c0a59-7f5b-4dc2-a8fb-6b4a2e8e1c31"),
                            Category = "Ticket",
                            CreatedAt = new DateTime(2026, 5, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ingresso comum para acesso ao evento.",
                            IsActive = true,
                            Name = "Ingresso Pista",
                            Price = 120.00m
                        },
                        new
                        {
                            Id = new Guid("2c91d6e4-3bb0-4b61-9b5c-f0b79a1d74e8"),
                            Category = "Ticket",
                            CreatedAt = new DateTime(2026, 5, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ingresso com acesso a área VIP.",
                            IsActive = true,
                            Name = "Ingresso VIP",
                            Price = 250.00m
                        },
                        new
                        {
                            Id = new Guid("b57e2f13-91f6-47c9-8f8e-2a0f3d6cbb92"),
                            Category = "Merchandise",
                            CreatedAt = new DateTime(2026, 5, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Camiseta oficial do evento.",
                            IsActive = true,
                            Name = "Camiseta Oficial",
                            Price = 80.00m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
