// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using inventory_service.Context;

#nullable disable

namespace inventory_service.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    partial class InventoryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("inventory_service.Entities.InventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("InventoryItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8c7a2bb8-8e0c-4a01-9a91-e5bcf55cf011"),
                            CreatedAt = new DateTime(2026, 5, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = new Guid("8f7c0a59-7f5b-4dc2-a8fb-6b4a2e8e1c31"),
                            Quantity = 100
                        },
                        new
                        {
                            Id = new Guid("efcbf096-7353-4803-84f4-a497c605d581"),
                            CreatedAt = new DateTime(2026, 5, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = new Guid("2c91d6e4-3bb0-4b61-9b5c-f0b79a1d74e8"),
                            Quantity = 50
                        },
                        new
                        {
                            Id = new Guid("d4f6d991-5ef7-4dd4-a2f2-772994d55a5d"),
                            CreatedAt = new DateTime(2026, 5, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = new Guid("b57e2f13-91f6-47c9-8f8e-2a0f3d6cbb92"),
                            Quantity = 30
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
